### ISSUE TITLE
KeyError: 'GGTGGGTG'

### ISSUE THREAD

**Issue by huangjx1001** [JonJala/mtag#100]
Hi,I am running mtag using 1trait, i met the following issue:
Trait 1: Dropped 1971 SNPs for duplicate values in the "snp_name" column
Dropped 920120 SNPs due to strand ambiguity, 4996132 SNPs remain in intersection after merging trait1
... Merge of GWAS summary statistics complete. Number of SNPs:	 4996132
Using 4996132 SNPs to estimate Omega (0 SNPs excluded due to strand ambiguity)
Estimating sigma..
'GGTGGGTG'
Traceback (most recent call last):
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/mtag.py", line 1567, in <module>
    mtag(args)
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/mtag.py", line 1351, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/mtag.py", line 468, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/ldsc_mod/ldscore/sumstats.py", line 442, in estimate_rg
    loop = _read_other_sumstats(args, log, None, sumstats, ref_ld_cnames,sumstats2=p2)
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/ldsc_mod/ldscore/sumstats.py", line 494, in _read_other_sumstats
    loop['Z2'] = _align_alleles(loop.Z2, alleles)
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/ldsc_mod/ldscore/sumstats.py", line 567, in _align_alleles
    z *= (-1) ** alleles.apply(lambda y: FLIP_ALLELES[y])
  File "/BIGDATA1/gzhmu_jli_1/.conda/envs/myenv_py2.7/lib/python2.7/site-packages/pandas/core/series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "/BIGDATA1/gzhmu_jli_1/software/mtag-master/ldsc_mod/ldscore/sumstats.py", line 567, in <lambda>
    z *= (-1) ** alleles.apply(lambda y: FLIP_ALLELES[y])
KeyError: 'GGTGGGTG'
Can anyone help? thx a lot!

**Comment by paturley** [comment]
Have you verified that the reference and alternate alleles in your data
only contain A, T, C, and G for every SNP?

**Comment by huangjx1001** [comment]
Sorry for the delayed reply. I checked my data, it only contain A, T, C, and G for every SNP, but i found one reference allele showed "AGGGTGGGTGGCGAGGGTCCCCTCACGCG", then I deleted this snp, after that I mtag again and the log showed the similar error "KeyError: 'GGGTGGGT'". I still confuse for this issue.

**Comment by paturley** [comment]
This still looks like an error with the reference or alternate alleles in
your data. Have you also checked the alternate allele column? Did you look
at the reference and alternate allele in your reference data set?

**Comment by huangjx1001** [comment]
You are right! I know where the problem is. Thanks a lot!

**Comment by paturley** [comment]
No problem. Glad to help.

**Comment by paturley** [comment]
I believe they just searched their summary statistics for SNPs that had
anything other than ATC of G as the reference or alternate allele.

**Comment by siminyu0629** [comment]
Thanks for your rapid reply, I have already check my data and delete the rows contain anything other than A, C, T and G, but the same error happens, the error log shows below:

2023/03/20/08:30:35 PM Estimating sigma..
2023/03/20/08:31:27 PM 'AAAA'
Traceback (most recent call last):
  File "mtag.py", line 1577, in <module>
    mtag(args)
  File "mtag.py", line 1358, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "mtag.py", line 472, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/Users/simon/Documents/01MedWork/2302_Gut_KS/05_Mtag/03_mtag/ldsc_mod/ldscore/sumstats.py", line 442, in estimate_rg
    loop = _read_other_sumstats(args, log, None, sumstats, ref_ld_cnames,sumstats2=p2)
  File "/Users/simon/Documents/01MedWork/2302_Gut_KS/05_Mtag/03_mtag/ldsc_mod/ldscore/sumstats.py", line 494, in _read_other_sumstats
    loop['Z2'] = _align_alleles(loop.Z2, alleles)
  File "/Users/simon/Documents/01MedWork/2302_Gut_KS/05_Mtag/03_mtag/ldsc_mod/ldscore/sumstats.py", line 567, in _align_alleles
    z *= (-1) ** alleles.apply(lambda y: FLIP_ALLELES[y])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "/Users/simon/Documents/01MedWork/2302_Gut_KS/05_Mtag/03_mtag/ldsc_mod/ldscore/sumstats.py", line 567, in <lambda>
    z *= (-1) ** alleles.apply(lambda y: FLIP_ALLELES[y])
KeyError: 'AAAA'
2023/03/20/08:31:27 PM Analysis terminated from error at Mon Mar 20 20:31:27 2023
2023/03/20/08:31:27 PM Total time elapsed: 6.0m:1.5s

Could anyone who solved this problem help ? thanks a lot !!

**Comment by paturley** [comment]
I'm fairly confident that your error implies that some SNP has a reference
or alternate allele of 'AAAA'. I would run a grep on your summary
statistics for 'AAAA' just to confirm.

**Comment by test12138jooh** [comment]
@SimonYu668  Hi！I have met the same issue, Have you fixed that? Does it mean the MTAG can only be applied to the SNV other than indel ?

**Comment by paturley** [comment]
The current MTAG software can only handle SNVs, though as you saw in
another issue, it sounds like it's not too complicated to edit your local
instance of MTAG to accept non-SNV data.
