### ISSUE TITLE
FloatingPointError: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by yabwei** [JonJala/mtag#105]
Hi,
The mtag runs pretty good all the time but it showed an error today when I was mtagging 2 gwas summary data (see log below). The 2 dataset has no problem when mtagging separately with other gwas summary data, meaning this is not due to data format issue etc. Could you provide any solutions ? Thanks so much. 

2020/08/14/05:54:35 PM Beginning MTAG calculations...
2020/08/14/05:55:54 PM  ... Completed MTAG calculations.
2020/08/14/05:55:54 PM Writing Phenotype 1 to file ...
2020/08/14/05:57:09 PM Writing Phenotype 2 to file ...
2020/08/14/05:57:11 PM divide by zero encountered in true_divide
Traceback (most recent call last):
  File "/home/disk3/weiyabin/tool/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/home/disk3/weiyabin/tool/mtag/mtag.py", line 1451, in mtag
    save_mtag_results(args, res_temp, Zs, N_raw, Fs, mtag_betas, mtag_se, mtag_factor)
  File "/home/disk3/weiyabin/tool/mtag/mtag.py", line 871, in save_mtag_results
    out_df['mtag_beta'] = mtag_betas[:,p] / weights
FloatingPointError: divide by zero encountered in true_divide
2020/08/14/05:57:11 PM Analysis terminated from error at Fri Aug 14 17:57:11 2020
2020/08/14/05:57:11 PM Total time elapsed: 13.0m:30.48s

**Comment by paturley** [comment]
Could you attach the full log file, please? It works make it a bit simpler
to diagnose what's going on.

**Comment by yabwei** [comment]
Hi,
I think I just found the answer in issue#32. He met the same problem.
The key is to filter allele freq <1.
One of my gwas summary data got a number of snps don't meet this. But the strange thing is that this dataset is ok to mtag with several other datasets.

I am really sorry my new run just overwrite the old log, which runs successfully now ! 🙂

Maybe you could highlight this freq filter criteria in the tutorial ?

Thanks again.
Best,
Yabin
________________________________

**Comment by paturley** [comment]
Ah. It probably makes the most sense to just change the code to filter
those variants out. We'll make an update to the software and push that
today.
