### ISSUE TITLE
AssertionError:  assert DATA_U.shape[0] == np.sum(np.asarray([x.shape[0] for x in comb_flat]))

### ISSUE THREAD

**Issue by pjordab** [JonJala/mtag#107]
Dear authors,

I'd like to ask for help for this new issue.

After doing mtag using this script:

~/projects/def-rtadros/tools/mtag/mtag.py --sumstats file1,file2,file3 --out ./mtag_metaformat --n_min 0.0 --force --meta_format --stream_stdout

I got the following error:

There are 72 SNPs present in Traits [0 3 4 5 6 7 8 9]
Beginning MTAG calculations...
 ... Completed MTAG calculations.
There are 1796780 SNPs present in Traits [0 1 2 4 7 8 9]
Beginning MTAG calculations...
 ... Completed MTAG calculations.

Traceback (most recent call last):
  File "/home/pjordab/projects/def-rtadros/tools/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/home/pjordab/projects/def-rtadros/tools/mtag/mtag.py", line 1441, in mtag
    assert DATA_U.shape[0] == np.sum(np.asarray([x.shape[0] for x in comb_flat]))
AssertionError
Analysis terminated from error at Thu Aug 20 14:00:23 2020

Do you know what could be the cause?

Many thanks for your help!

Paloma

**Comment by pjordab** [comment]
Thank you very much for your responses. Please let us know when the meta-format option is available.

**Comment by paturley** [comment]
Hello Paloma,

Sorry this has continued to take time to resolve. A combination of
deadlines and covid complications have made it hard to make time to clean
up this more complicated part of the code. If this is urgent for you, one
option you may consider is running MTAG on subsets of cohorts manually
yourself and keeping the estimate that corresponds to the largest sample
size. This is approximately what the metaformat option is meant to do in
the first place, and it's likely that you could do this by hand more
quickly than we could fix and test the code.

Best,
Patrick

**Comment by pjordab** [comment]
Hi Patrick and developers,
Thanks for all your previous answers and help. 
I have reattempted the same analysis and got the same error when using MTAG on 4 traits with the meta_format option.  
Since I find this option of your tool very interesting, I was wondering if you have been able to sort out this part of the code.
Thank you very much, 
Paloma.

**Comment by paturley** [comment]
Hi Paloma,

Unfortunately, we have not had time to make these updates to the MTAG
software. It's on our todo list, but (perhaps unsurprisingly) the todo list
of an academic is very long... Sorry we cannot be of more help.

Best,
Patrick

**Comment by pjordab** [comment]
That's perfectly understandable. Thank you very much!
