### ISSUE TITLE
KeyError: 'CHR0'

### ISSUE THREAD

**Issue by gianolga** [JonJala/mtag#110]
Hello Authors,

I am trying to run mtag for 1 trait. The munging run successfully (7276895 SNPs remain) but then I meet the following issue:

2020/08/26/03:35:48 PM Dropped 1147433 SNPs due to strand ambiguity, 6129462 SNPs remain in intersection after merging trait1
2020/08/26/03:35:48 PM ... Merge of GWAS summary statistics complete. Number of SNPs:	 6129462
2020/08/26/03:35:58 PM 'CHR0'
Traceback (most recent call last):
  File "/SAN/ugi/ukhls/bin/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/SAN/ugi/ukhls/bin/mtag/mtag.py", line 1339, in mtag
    Zs , Ns ,Fs, res_temp, DATA, N_raw = extract_gwas_sumstats(DATA,args,list(np.arange(args.P)))
  File "/SAN/ugi/ukhls/bin/mtag/mtag.py", line 604, in extract_gwas_sumstats
    results_template.loc[:,col] = DATA[col+str(t0[0])]
  File "/home/ogiannak/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2062, in __getitem__
    return self._getitem_column(key)
  File "/home/ogiannak/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2069, in _getitem_column
    return self._get_item_cache(key)
  File "/home/ogiannak/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1534, in _get_item_cache
    values = self._data.get(item)
  File "/home/ogiannak/.local/lib/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/home/ogiannak/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2395, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5239)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5085)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1207, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20405)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1215, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20359)
KeyError: 'CHR0'

The summary statistics don't have any chr/pos info, but all the necessary columns as specified in wiki are there. Could you please assist me with this? 

Many thanks,
Olga

**Comment by paturley** [comment]
I think the chr and bpos columns are necessary to run the LD score
regression part of the software. From the wiki:

These sample files are already formatted in the default output accepted by
the command line tool. That is, they are whitespace-delimited .txt files
with the following column names (the specific order is not necessary):

snpid    chr    bpos    a1    a2    freq    z    pval    n

Do you have a snpid column? Maybe you can merge your summary statistics
with a reference dataset that matches snpid to chir and bpos.

Best,
Patrick

**Comment by gianolga** [comment]
I see, I have the columns necessary for MTAG, i.e. snpid, a1/a2, n, freq and z. I'll hoping I can skip this step but I'll try to get the chr/pos from a reference panel as you suggested. I'll keep this open just in case it doesn't work. Many thanks! Olga

**Comment by gianolga** [comment]
It's working now!! Many thanks!!
