### ISSUE TITLE
Termination of analysis

### ISSUE THREAD

**Issue by Nalinikanta7** [JonJala/mtag#177]
I got the following result while running mtag. Kindly help me in this regard.

2023/03/24/11:14:00 AM Beginning MTAG analysis...
2023/03/24/11:14:00 AM MTAG will use the Z column for analyses.
2023/03/24/11:14:00 AM invalid literal for int() with base 10: 'n'
Traceback (most recent call last):
  File "./mtag.py", line 1577, in <module>
    mtag(args)
  File "./mtag.py", line 1343, in mtag
    DATA_U, DATA, args = load_and_merge_data(args)
  File "./mtag.py", line 257, in load_and_merge_data
    args.n_list = [int(x) for x in args.n_value.split(',')]
ValueError: invalid literal for int() with base 10: 'n'
2023/03/24/11:14:00 AM Analysis terminated from error at Fri Mar 24 11:14:00 2023
2023/03/24/11:14:00 AM Total time elapsed: 0.0s

**Comment by JonJala** [comment]
What does your invocation of MTAG look like?  (As in what parameters are
you passing?). It looks like you're passing in an 'n' when it expects a
number, based on the error that was returned.

**Comment by Nalinikanta7** [comment]
Can you provide the example data link as the data provided here through the link cannot be unzipped?

**Comment by JonJala** [comment]
I'm sorry, but I don't understand what you mean.  What data and what link?
